### ISSUE TITLE
LoadProhibited). Exception was unhandled. While getting characteristics

### ISSUE THREAD

**Issue by petrkr** [basecue/micropython-blesync-client#2]
Service described as follow:
```
class MyClass(blesync_client.Service):
    uuid = bluetooth.UUID('e7810a71-73ae-499d-8c15-faa9aef0c3f2')
    _tx = blesync_client.Characteristic(bluetooth.UUID('bef8d6c9-9c21-4c9e-b632-bd58c1009f9f'))
    
    def send(self, data):
        self._tx.write(data)
```

main.py
```
import bluetooth
import blesync_client

client = blesync_client.BLEClient(MyService)
client.connect(0, addr)
```

```
I (69610) BTDM_INIT: BT controller compile version [e989f20]
I (85845) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (85955) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
GAP procedure initiated: connect; peer_addr_type=0 peer_addr=66:22:ad:96:31:2b scan_itvl=16 scan_window=16 itvl_min=24 itvl_max=40 latency=0 supervision_timeout=256 min_ce_len=10
GATT procedure initiated: discover all services                                                                                                                                   
GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=6 itvl_max=12 latency=0 supervision_timeout=550 min_ce_len=16 max_ce_len=768
GATT procedure initiated: discover all characteristics; start_handle=13 end_handle=16
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40159cc8  PS      : 0x00060e30  A0      : 0x80163063  A1      : 0x3ffd0e90  
A2      : 0x3ffc5610  A3      : 0x00000000  A4      : 0x3f42e281  A5      : 0x3f4028a0  
A6      : 0x3f43396a  A7      : 0x3f4339d0  A8      : 0x00000000  A9      : 0x3ffd0e50  
A10     : 0x3ffc5610  A11     : 0x00000000  A12     : 0x00000004  A13     : 0x3ffd0e90  
A14     : 0x00000003  A15     : 0x3ffc38c0  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000004  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  
```

**Comment by petrkr** [comment]
More debug from GDB:

Sometimes (mostly first run):
```
GATT procedure initiated: discover all services
Traceback (most recent call last):
  File "blesync.py", line 36, in _call_callbacks
KeyError: 128
```

**Comment by petrkr** [comment]
More debug from micropython (based on latest dev)

maybe it's connected with more services/chars?


NOT working printer char
```
=== client = blesync_client.BLEClient(POSPrinterService)                                                            
=== ser = client.connect(0, b'f"\xad\x961+')                                                                        
===                                                                                                                 
===                                                                                                                 
init chracteristic                                                                                                  
I (12720) BTDM_INIT: BT controller compile version [e989f20]
I (25745) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (25855) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
GAP procedure initiated: connect; peer_addr_type=0 peer_addr=66:22:ad:96:31:2b scan_itvl=16 scan_window=16 itvl_min0
blesync IRQ: 64, (0, 0, b'f"\xad\x961+')                                                                            
calling event with data: 64, 0, (0, b'f"\xad\x961+')                                                                
GATT procedure initiated: discover all services                                                                     
GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=6 itvl_max=12 latency=0 supervision_ti8
blesync IRQ: 256, (0, 1, 3, UUID16(0x1800))                                                                         
calling event with data: 256, (1, 3, UUID16(0x1800)), 0                                                             
blesync IRQ: 256, (0, 4, 6, UUID16(0x1801))                                                                         
calling event with data: 256, (4, 6, UUID16(0x1801)), 0                                                             
Start for class 1, 3, UUID16(0x1801)                                                                                
service: <class 'POSPrinterService'>                                                                                
Start for class 4, 6, UUID16(0x1801)                                                                                
service: <class 'POSPrinterService'>                                                                                
blesync IRQ: 256, (0, 7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455'))                                       
calling event with data: 256, (7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455')), 0                           
Start for class 7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455')                                              
service: <class 'POSPrinterService'>                                                                                
blesync IRQ: 256, (0, 13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2'))                                      
calling event with data: 256, (13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2')), 0                          
Start for class 13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2')                                             
service: <class 'POSPrinterService'>                                                                                
init service                                                                                                        
service get char                                                                                                    
get char name: __class__                                                                                            
get char name: __init__                                                                                             
get char name: __module__                                                                                           
get char name: __name__                                                                                             
get char name: __qualname__                                                                                         
get char name: print                                                                                                
get char name: __bases__                                                                                            
get char name: uuid                                                                                                 
get char name: _tx                                                                                                  
get char name: _on_gattc_message                                                                                    
get char name: _get_characteristics                                                                                 
got chars: [<Characteristic object at 3ffe6690>]                                                                    
blesync: gattc_discover_characteristics                                                                             
blesync: start discover                                                                                             
GATT procedure initiated: discover all characteristics; start_handle=13 end_handle=16                               
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync IRQ: 256, (0, 17, 22, UUID16(0x18f0))                                                                       
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.                                  
Core 1 register dump:                                                                                               
PC      : 0x4015a108  PS      : 0x00060430  A0      : 0x801634a3  A1      : 0x3ffd0e80                              
A2      : 0x3ffc5608  A3      : 0x00000000  A4      : 0x3f42fc59  A5      : 0x3f4028eb                              
A6      : 0x3f435342  A7      : 0x3f4353a8  A8      : 0x00000000  A9      : 0x3ffd0e40                              
A10     : 0x3ffc5608  A11     : 0x00000000  A12     : 0x00000004  A13     : 0x3ffd0e80                              
A14     : 0x00000003  A15     : 0x3ffc38b8  SAR     : 0x00000010  EXCCAUSE: 0x0000001c                              
EXCVADDR: 0x00000004  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000                              

ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000                                   

Backtrace: 0x4015a108:0x3ffd0e80 0x401634a0:0x3ffd0eb0 0x40162fa5:0x3ffd0ef0 0x4015c9c5:0x3ffd0f20 0x4015b2c5:0x3ff0

Rebooting...                                                                                                        
ets Jun  8 2016 00:22:57   
```


Working UART server:
```

>>> client.connect(0, b'<q\xbf\x9e\x13N')                                                                           
GAP procedure initiated: stop advertising.                                                                          
GAP procedure initiated: connect; peer_addr_type=0 peer_addr=3c:71:bf:9e:13:4e scan_itvl=16 scan_window=16 itvl_min0
blesync IRQ: 64, (0, 0, b'<q\xbf\x9e\x13N')                                                                         
calling event with data: 64, 0, (0, b'<q\xbf\x9e\x13N')                                                             
GATT procedure initiated: discover all services                                                                     
blesync IRQ: 256, (0, 1, 5, UUID16(0x1800))                                                                         
calling event with data: 256, (1, 5, UUID16(0x1800)), 0                                                             
blesync IRQ: 256, (0, 6, 10, UUID16(0x1800))                                                                        
calling event with data: 256, (6, 10, UUID16(0x1800)), 0                                                            
Start for class 1, 5, UUID16(0x1800)                                                                                
service: <class 'UARTService'>                                                                                      
Start for class 6, 10, UUID16(0x1800)                                                                               
service: <class 'UARTService'>                                                                                      
blesync IRQ: 256, (0, 11, 65535, UUID128('6e400001-b5a3-f393-e0a9-e50e24dcca9e'))                                   
calling event with data: 256, (11, 65535, UUID128('6e400001-b5a3-f393-e0a9-e50e24dcca9e')), 0                       
Start for class 11, 65535, UUID128('6e400001-b5a3-f393-e0a9-e50e24dcca9e')                                          
service: <class 'UARTService'>                                                                                      
init service                                                                                                        
service get char                                                                                                    
get char name: __class__                                                                                            
get char name: __init__                                                                                             
get char name: __module__                                                                                           
get char name: __name__                                                                                             
get char name: __qualname__                                                                                         
get char name: send                                                                                                 
get char name: __bases__                                                                                            
get char name: _on_gattc_message                                                                                    
get char name: uuid                                                                                                 
get char name: on_message                                                                                           
get char name: _get_characteristics                                                                                 
get char name: _rx                                                                                                  
get char name: _tx                                                                                                  
got chars: [<Characteristic object at 3ffe8970>, <Characteristic object at 3ffe89c0>]                               
blesync: gattc_discover_characteristics                                                                             
blesync: start discover                                                                                             
GATT procedure initiated: discover all characteristics; start_handle=11 end_handle=65535                            
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?              
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync IRQ: 512, (0, 12, 13, 18, UUID128('6e400003-b5a3-f393-e0a9-e50e24dcca9e'))                                  
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: while queue                                                                                                
char: 12 13 18 UUID128('6e400003-b5a3-f393-e0a9-e50e24dcca9e')                                                      
charinit: trying register                                                                                           
charinit: except                                                                                                    
charinit: trying register                                                                                           
register UUID128('6e400003-b5a3-f393-e0a9-e50e24dcca9e'), <UARTService object at 3fffdec0>, 13                      
charinit: else                                                                                                      
blesync: after yield                                                                                                
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle                                                                                                       
blesync: while true                                                                                                 
blesync: timeoit?                                                                                                   
blesync: idle
blesync: while true
blesync: timeoit?
blesync: idle
blesync: while true
blesync: timeoit?
blesync: idle
blesync: while true
blesync: timeoit?
blesync: idle
blesync: while true
blesync: timeoit?
blesync: idle
blesync: while true
blesync: timeoit?
blesync IRQ: 512, (0, 15, 16, 8, UUID128('6e400002-b5a3-f393-e0a9-e50e24dcca9e'))
blesync: idle
blesync: while true
blesync: while queue
char: 15 16 8 UUID128('6e400002-b5a3-f393-e0a9-e50e24dcca9e')
charinit: trying register
register UUID128('6e400002-b5a3-f393-e0a9-e50e24dcca9e'), <UARTService object at 3fffdec0>, 16
charinit: else
service setdefault
{<class 'UARTService'>: [<UARTService object at 3fffdec0>]}
>>> 
```

**Comment by petrkr** [comment]
tested from command line by using generic micropython `bluetooth` module

```
>>> import bluetooth
>>> ble = bluetooth.BLE()
>>> ble.active(1)

I (150840) BTDM_INIT: BT controller compile version [e989f20]
I (167768) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (167878) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
True

>>> def i(event, data):
...    print(event, data)

>>> ble.irq(i)  

>>> ble.gap_scan(2000)                                                                                                                                                  
GAP procedure initiated: discovery; own_addr_type=0 filter_policy=0 passive=0 limited=0 filter_duplicates=0 duration=2000ms                                             
16 (0, b'f"\xad\x961+', 0, -62, b'\x02\x01\n\x03\x02\xf0\x18\x11\x06\xf2\xc3\xf0\xae\xa9\xfa\x15\x8c\x9dI\xaesq\n\x81\xe7')                                         
16 (0, b'f"\xad\x961+', 4, -61, b'\r\tPETR-PRINTER')                                                                                                                    
16 (1, b'h\xf7\xf5\x07r\xac', 0, -84, b'\x02\x01\x1a\x02\n\x0c\x0b\xffL\x00\x10\x06\x13\x1e%\xf6\xe5\xa9')                                                              
16 (1, b'h\xf7\xf5\x07r\xac', 4, -86, b'')                                                                                                                              
32 ()                                                                                                                                                                   

>>> printer = ble.gap_connect(0, b'f"\xad\x961+')                                                                                                                       

GAP procedure initiated: connect; peer_addr_type=0 peer_addr=66:22:ad:96:31:2b scan_itvl=16 scan_window=16 itvl_min=24 itvl_max=40 latency=0 supervision_timeout=256 mi0
64 (0, 0, b'f"\xad\x961+')                                                                                                                                          
GAP procedure initiated: connection parameter update; conn_handle=0 itvl_min=6 itvl_max=12 latency=0 supervision_timeout=550 min_ce_len=16 max_ce_len=768               

>>> services = ble.gattc_discover_services(0)
GATT procedure initiated: discover all services
256 (0, 1, 3, UUID16(0x1800))
256 (0, 4, 6, UUID16(0x1801))
256 (0, 7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455'))
256 (0, 13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2'))
256 (0, 17, 22, UUID16(0x18f0))
256 (0, 23, 37, UUID16(0x180a))

>>> chars = ble.gattc_discover_characteristics(0, 13, 16)
GATT procedure initiated: discover all characteristics; start_handle=13 end_handle=16
512 (0, 14, 15, 62, UUID128('bef8d6c9-9c21-4c9e-b632-bd58c1009f9f'))

GATT procedure initiated: write no rsp; att_handle=15 len=1
>>> ble.gattc_write(0, 15, b'hoj z uPy\x0d')
GATT procedure initiated: write no rsp; att_handle=15 len=10
>>> ble.gattc_write(0, 15, b'hoj z uPy\x0d')
GATT procedure initiated: write no rsp; att_handle=15 len=10
>>> ble.gattc_write(0, 15, b'\x0d')
GATT procedure initiated: write no rsp; att_handle=15 len=1
>>> ble.gattc_write(0, 15, b'\x0d')
GATT procedure initiated: write no rsp; att_handle=15 len=1
```

![20200515_222848](https://user-images.githubusercontent.com/6428351/82093665-d99b1b00-96fb-11ea-9a96-fa2e949db4b1.jpg)

**Comment by petrkr** [comment]
debug messages done by this 

https://github.com/petrkr/octopuslab/commit/945db2641146e9e7aa51f3ca9b156495d3ce2204

**Comment by petrkr** [comment]
OK, it because yield in blesync.py

If I will rewrite it to simple wait-list it's working properly

https://github.com/petrkr/octopuslab/commit/f39d286ab1e4c901bffd9e8119871569cb01b3c9


```
=== client = blesync_client.BLEClient(POSPrinterService)                                                                                                                
=== ser = client.connect(0, b'f"\xad\x961+')                                                                                                                            
===                                                                                                                                                                     
init chracteristic                                                                                                                                                      
blesync IRQ: 64, (0, 0, b'f"\xad\x961+')                                                                                                                                
calling event with data: 64, 0, (0, b'f"\xad\x961+')                                                                                                                    
blesync IRQ: 256, (0, 1, 3, UUID16(0x1800))                                                                                                                             
calling event with data: 256, (1, 3, UUID16(0x1800)), 0                                                                                                                 
blesync IRQ: 256, (0, 4, 6, UUID16(0x1801))                                                                                                                             
calling event with data: 256, (4, 6, UUID16(0x1801)), 0                                                                                                                 
blesync IRQ: 256, (0, 7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455'))                                                                                           
calling event with data: 256, (7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455')), 0                                                                               
blesync IRQ: 256, (0, 13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2'))                                                                                          
calling event with data: 256, (13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2')), 0                                                                              
blesync IRQ: 256, (0, 17, 22, UUID16(0x18f0))                                                                                                                           
calling event with data: 256, (17, 22, UUID16(0x18f0)), 0                                                                                                               
blesync IRQ: 256, (0, 23, 37, UUID16(0x180a))                                                                                                                           
calling event with data: 256, (23, 37, UUID16(0x180a)), 0                                                                                                               
Start for class 1, 3, UUID16(0x1801)                                                                                                                                    
service: <class 'POSPrinterService'>                                                                                                                                    
Start for class 4, 6, UUID16(0x1801)                                                                                                                                    
service: <class 'POSPrinterService'>                                                                                                                                    
Start for class 7, 12, UUID128('49535343-fe7d-4ae5-8fa9-9fafd205e455')                                                                                                  
service: <class 'POSPrinterService'>                                                                                                                                    
Start for class 13, 16, UUID128('e7810a71-73ae-499d-8c15-faa9aef0c3f2')                                                                                                 
service: <class 'POSPrinterService'>                                                                                                                                    
init service                                                                                                                                                            
service get char                                                                                                                                                        
get char name: __class__                                                                                                                                                
get char name: __init__                                                                                                                                                 
get char name: __module__                                                                                                                                               
get char name: __name__                                                                                                                                                 
get char name: __qualname__                                                                                                                                             
get char name: print                                                                                                                                                    
get char name: __bases__                                                                                                                                                
get char name: uuid                                                                                                                                                     
get char name: _tx                                                                                                                                                      
get char name: _on_gattc_message                                                                                                                                        
get char name: _get_characteristics                                                                                                                                     
got chars: [<Characteristic object at 3ffe6690>]                                                                                                                        
blesync: gattc_discover_characteristics                                                                                                                                 
blesync: start discover                                                                                                                                                 
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true                                                                                                                                                     
blesync: timeoit?                                                                                                                                                       
blesync: idle                                                                                                                                                           
blesync: while true
blesync IRQ: 512, (0, 14, 15, 62, UUID128('bef8d6c9-9c21-4c9e-b632-bd58c1009f9f'))
blesync: while queue
char: 14 15 62 UUID128('bef8d6c9-9c21-4c9e-b632-bd58c1009f9f')
charinit: trying register
register UUID128('bef8d6c9-9c21-4c9e-b632-bd58c1009f9f'), <POSPrinterService object at 3ffeaa60>, 15
charinit: else
service setdefault
Start for class 17, 22, UUID16(0x180a)
service: <class 'POSPrinterService'>
Start for class 23, 37, UUID16(0x180a)
service: <class 'POSPrinterService'>
>>> ser
{<class 'POSPrinterService'>: [<POSPrinterService object at 3ffeaa60>]}
>>> ser[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 0
>>> ser[POSPrinterService]
[<POSPrinterService object at 3ffeaa60>]
>>> ser[POSPrinterService][0]
<POSPrinterService object at 3ffeaa60>
>>> ser[POSPrinterService][0].print("Ahoj")
get characteristic <POSPrinterService object at 3ffeaa60>
>>> ser[POSPrinterService][0].print("Ahoj\n")
get characteristic <POSPrinterService object at 3ffeaa60>
>>> ser[POSPrinterService][0].print("Ahoj 123\n")
get characteristic <POSPrinterService object at 3ffeaa60>
>>> ser[POSPrinterService][0].print("\n")
get characteristic <POSPrinterService object at 3ffeaa60>
>>> ser.
__class__       __delitem__     __getitem__     __setitem__
clear           copy            get             items
keys            pop             popitem         setdefault
update          values          fromkeys
>>> dir(ser[POSPrinterService][0])
get characteristic <POSPrinterService object at 3ffeaa60>
['__class__', '__init__', '__module__', '__qualname__', 'print', '__dict__', 'uuid', '_tx', '_on_gattc_message', 'conn_handle', '_get_characteristics', '_characteristi]
>>> 
```

**Comment by petrkr** [comment]
Fixed in dependent issue
